"""add avatar to user

Revision ID: bad723d17079
Revises: 78ba13627e4a
Create Date: 2024-08-04 20:46:51.857854

"""



revision = 'bad723d17079'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
