name: Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        cd ./backend
        python -m venv venv
        source ./venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install pdm
        pdm install

    - name: Lint with Ruff
      run: |
        cd ./backend
        source ./venv/bin/activate
        pdm check
